version: 1.0.{build}

configuration:
- Debug
- Release

environment:
  matrix:
  - VS_VERSION: 12
    VS_PLATFORM: x64
  - VS_VERSION: 14
    VS_PLATFORM: x64

before_build:
- cd thirdparty
- cmake -P downloadPackages.cmake
- cd ..
- cmake -H. -BBuild -G "Visual Studio %VS_VERSION%" -DCMAKE_GENERATOR_PLATFORM=%VS_PLATFORM%

build:
  project: Build\AliyunOpenSearchSDK.sln

